// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqK7fi3duxhzuXiwTF1yI3759Icd7IemE',
    appId: '1:579258399818:web:49933ea6a116d913527ab3',
    messagingSenderId: '579258399818',
    projectId: 'movie-discovery-9460c',
    authDomain: 'movie-discovery-9460c.firebaseapp.com',
    storageBucket: 'movie-discovery-9460c.firebasestorage.app',
    measurementId: 'G-WSMF0C2NNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Actual-Key',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'movie-discovery-demo',
    storageBucket: 'movie-discovery-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Actual-Key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'movie-discovery-demo',
    storageBucket: 'movie-discovery-demo.appspot.com',
    iosBundleId: 'com.example.movieDiscovery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Actual-Key',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'movie-discovery-demo',
    storageBucket: 'movie-discovery-demo.appspot.com',
  );
}
